requests.path=./requests.json
crawler.path=./crawler.json
server.port=9191
fixture.path=./newFixtures
g3.url=http://mn4sg3xappw101.ideasstg.int:8080
default.response.code=200
default.response.body=success